/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class example_BsDiff */

#ifndef _Included_example_BsDiff
#define _Included_example_BsDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_BsDiff
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jstring JNICALL Java_example_BsDiff_diff
  (JNIEnv *, jclass ,jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
