# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "D:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "D:\Program Files\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\C++\Update

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\C++\Update

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	echo >nul && "D:\Program Files\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache

.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "D:\Program Files\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache

.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\C++\Update\CMakeFiles D:\C++\Update\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\C++\Update\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean

.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Update

# Build rule for target.
Update: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) Update
.PHONY : Update

# fast build rule for target.
Update\fast:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\build
.PHONY : Update\fast

blocksort.obj: blocksort.c.obj

.PHONY : blocksort.obj

# target to build an object file
blocksort.c.obj:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\blocksort.c.obj
.PHONY : blocksort.c.obj

blocksort.i: blocksort.c.i

.PHONY : blocksort.i

# target to preprocess a source file
blocksort.c.i:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\blocksort.c.i
.PHONY : blocksort.c.i

blocksort.s: blocksort.c.s

.PHONY : blocksort.s

# target to generate assembly for a file
blocksort.c.s:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\blocksort.c.s
.PHONY : blocksort.c.s

bsdiff.obj: bsdiff.cpp.obj

.PHONY : bsdiff.obj

# target to build an object file
bsdiff.cpp.obj:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\bsdiff.cpp.obj
.PHONY : bsdiff.cpp.obj

bsdiff.i: bsdiff.cpp.i

.PHONY : bsdiff.i

# target to preprocess a source file
bsdiff.cpp.i:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\bsdiff.cpp.i
.PHONY : bsdiff.cpp.i

bsdiff.s: bsdiff.cpp.s

.PHONY : bsdiff.s

# target to generate assembly for a file
bsdiff.cpp.s:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\bsdiff.cpp.s
.PHONY : bsdiff.cpp.s

bzlib.obj: bzlib.c.obj

.PHONY : bzlib.obj

# target to build an object file
bzlib.c.obj:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\bzlib.c.obj
.PHONY : bzlib.c.obj

bzlib.i: bzlib.c.i

.PHONY : bzlib.i

# target to preprocess a source file
bzlib.c.i:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\bzlib.c.i
.PHONY : bzlib.c.i

bzlib.s: bzlib.c.s

.PHONY : bzlib.s

# target to generate assembly for a file
bzlib.c.s:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\bzlib.c.s
.PHONY : bzlib.c.s

compress.obj: compress.c.obj

.PHONY : compress.obj

# target to build an object file
compress.c.obj:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\compress.c.obj
.PHONY : compress.c.obj

compress.i: compress.c.i

.PHONY : compress.i

# target to preprocess a source file
compress.c.i:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\compress.c.i
.PHONY : compress.c.i

compress.s: compress.c.s

.PHONY : compress.s

# target to generate assembly for a file
compress.c.s:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\compress.c.s
.PHONY : compress.c.s

crctable.obj: crctable.c.obj

.PHONY : crctable.obj

# target to build an object file
crctable.c.obj:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\crctable.c.obj
.PHONY : crctable.c.obj

crctable.i: crctable.c.i

.PHONY : crctable.i

# target to preprocess a source file
crctable.c.i:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\crctable.c.i
.PHONY : crctable.c.i

crctable.s: crctable.c.s

.PHONY : crctable.s

# target to generate assembly for a file
crctable.c.s:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\crctable.c.s
.PHONY : crctable.c.s

decompress.obj: decompress.c.obj

.PHONY : decompress.obj

# target to build an object file
decompress.c.obj:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\decompress.c.obj
.PHONY : decompress.c.obj

decompress.i: decompress.c.i

.PHONY : decompress.i

# target to preprocess a source file
decompress.c.i:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\decompress.c.i
.PHONY : decompress.c.i

decompress.s: decompress.c.s

.PHONY : decompress.s

# target to generate assembly for a file
decompress.c.s:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\decompress.c.s
.PHONY : decompress.c.s

huffman.obj: huffman.c.obj

.PHONY : huffman.obj

# target to build an object file
huffman.c.obj:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\huffman.c.obj
.PHONY : huffman.c.obj

huffman.i: huffman.c.i

.PHONY : huffman.i

# target to preprocess a source file
huffman.c.i:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\huffman.c.i
.PHONY : huffman.c.i

huffman.s: huffman.c.s

.PHONY : huffman.s

# target to generate assembly for a file
huffman.c.s:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\huffman.c.s
.PHONY : huffman.c.s

randtable.obj: randtable.c.obj

.PHONY : randtable.obj

# target to build an object file
randtable.c.obj:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\randtable.c.obj
.PHONY : randtable.c.obj

randtable.i: randtable.c.i

.PHONY : randtable.i

# target to preprocess a source file
randtable.c.i:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\randtable.c.i
.PHONY : randtable.c.i

randtable.s: randtable.c.s

.PHONY : randtable.s

# target to generate assembly for a file
randtable.c.s:
	$(MAKE) -f CMakeFiles\Update.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\Update.dir\randtable.c.s
.PHONY : randtable.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... Update
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... blocksort.obj
	@echo ... blocksort.i
	@echo ... blocksort.s
	@echo ... bsdiff.obj
	@echo ... bsdiff.i
	@echo ... bsdiff.s
	@echo ... bzlib.obj
	@echo ... bzlib.i
	@echo ... bzlib.s
	@echo ... compress.obj
	@echo ... compress.i
	@echo ... compress.s
	@echo ... crctable.obj
	@echo ... crctable.i
	@echo ... crctable.s
	@echo ... decompress.obj
	@echo ... decompress.i
	@echo ... decompress.s
	@echo ... huffman.obj
	@echo ... huffman.i
	@echo ... huffman.s
	@echo ... randtable.obj
	@echo ... randtable.i
	@echo ... randtable.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

